<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DtcCenterInventorySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('dtc_center_inventories')->insert([
            [
                'congressional_district' => '1st District',
                'province' => 'Surigao del Norte',
                'municipality_city' => 'Surigao City',
                'barangay' => 'Canlanipa',
                'center_name' => 'Surigao City DTC Poblacion Center',
                'longitude' => 125.4949,
                'latitude' => 9.7892,
                'verified' => true,
                'moa_date_of_signing' => '2023-03-15',
                'date_of_launching' => '2023-06-01',
                'date_of_platform_registration' => '2023-06-10',
                'tcms_status' => 'Registered',
                'tcms_key' => 'SDN-001',
                'tcms_identifier' => 'TCMS-SDN-0001',
                'tcms_verification_status' => 'Verified',
                'odk_status' => 'Published',
                'connectivity_status' => 'Connected',
                'type_of_center_host' => 'LGU',
                'operational_status' => 'Operational',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'congressional_district' => '1st District',
                'province' => 'Surigao del Norte',
                'municipality_city' => 'Surigao City',
                'barangay' => 'Bonifacio',
                'center_name' => 'Bonifacio Barangay Digital Hub',
                'longitude' => 125.5160,
                'latitude' => 9.7850,
                'verified' => true,
                'moa_date_of_signing' => '2023-08-20',
                'date_of_launching' => '2023-10-05',
                'date_of_platform_registration' => '2023-10-12',
                'tcms_status' => 'Registered',
                'tcms_key' => 'SDN-002',
                'tcms_identifier' => 'TCMS-SDN-0002',
                'tcms_verification_status' => 'Verified',
                'odk_status' => 'Published',
                'connectivity_status' => 'Connected',
                'type_of_center_host' => 'Barangay',
                'operational_status' => 'Operational',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'congressional_district' => '1st District',
                'province' => 'Surigao del Norte',
                'municipality_city' => 'Claver',
                'barangay' => 'Poblacion',
                'center_name' => 'Claver Municipal DTC',
                'longitude' => 125.7320,
                'latitude' => 9.5712,
                'verified' => true,
                'moa_date_of_signing' => '2022-11-10',
                'date_of_launching' => '2023-01-20',
                'date_of_platform_registration' => '2023-01-28',
                'tcms_status' => 'Registered',
                'tcms_key' => 'SDN-003',
                'tcms_identifier' => 'TCMS-SDN-0003',
                'tcms_verification_status' => 'Verified',
                'odk_status' => 'Published',
                'connectivity_status' => 'Connected',
                'type_of_center_host' => 'LGU',
                'operational_status' => 'Operational',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'congressional_district' => '1st District',
                'province' => 'Surigao del Norte',
                'municipality_city' => 'Placer',
                'barangay' => 'Poblacion',
                'center_name' => 'Placer Tech Hub',
                'longitude' => 125.6020,
                'latitude' => 9.6540,
                'verified' => true,
                'moa_date_of_signing' => '2023-02-14',
                'date_of_launching' => '2023-04-01',
                'date_of_platform_registration' => '2023-04-08',
                'tcms_status' => 'Registered',
                'tcms_key' => 'SDN-004',
                'tcms_identifier' => 'TCMS-SDN-0004',
                'tcms_verification_status' => 'Verified',
                'odk_status' => 'Published',
                'connectivity_status' => 'Connected',
                'type_of_center_host' => 'LGU',
                'operational_status' => 'Operational',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'congressional_district' => '1st District',
                'province' => 'Surigao del Norte',
                'municipality_city' => 'Dapa',
                'barangay' => 'Poblacion',
                'center_name' => 'Dapa (Siargao) Tech Hub',
                'longitude' => 126.0543,
                'latitude' => 9.7562,
                'verified' => true,
                'moa_date_of_signing' => '2023-05-05',
                'date_of_launching' => '2023-07-15',
                'date_of_platform_registration' => '2023-07-22',
                'tcms_status' => 'Registered',
                'tcms_key' => 'SDN-005',
                'tcms_identifier' => 'TCMS-SDN-0005',
                'tcms_verification_status' => 'Verified',
                'odk_status' => 'Published',
                'connectivity_status' => 'Connected',
                'type_of_center_host' => 'LGU',
                'operational_status' => 'Operational',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'congressional_district' => '1st District',
                'province' => 'Surigao del Norte',
                'municipality_city' => 'Mainit',
                'barangay' => 'Poblacion',
                'center_name' => 'Mainit Municipal DTC',
                'longitude' => 125.5231,
                'latitude' => 9.5372,
                'verified' => true,
                'moa_date_of_signing' => '2023-09-01',
                'date_of_launching' => '2023-11-12',
                'date_of_platform_registration' => '2023-11-19',
                'tcms_status' => 'Registered',
                'tcms_key' => 'SDN-006',
                'tcms_identifier' => 'TCMS-SDN-0006',
                'tcms_verification_status' => 'Verified',
                'odk_status' => 'Published',
                'connectivity_status' => 'Connected',
                'type_of_center_host' => 'LGU',
                'operational_status' => 'Operational',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'congressional_district' => '2nd District',
                'province' => 'Surigao del Norte',
                'municipality_city' => 'Del Carmen',
                'barangay' => 'Poblacion',
                'center_name' => 'Del Carmen Digital Center',
                'longitude' => 125.9770,
                'latitude' => 9.8690,
                'verified' => false,
                'moa_date_of_signing' => '2024-01-10',
                'date_of_launching' => null,
                'date_of_platform_registration' => null,
                'tcms_status' => 'Pending',
                'tcms_key' => 'SDN-007',
                'tcms_identifier' => 'TCMS-SDN-0007',
                'tcms_verification_status' => 'Pending',
                'odk_status' => 'Draft',
                'connectivity_status' => 'Pending',
                'type_of_center_host' => 'LGU',
                'operational_status' => 'Under Construction',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'congressional_district' => '2nd District',
                'province' => 'Surigao del Norte',
                'municipality_city' => 'San Francisco',
                'barangay' => 'Poblacion',
                'center_name' => 'San Francisco Municipal DTC',
                'longitude' => 125.9400,
                'latitude' => 9.7780,
                'verified' => true,
                'moa_date_of_signing' => '2023-12-05',
                'date_of_launching' => '2024-02-20',
                'date_of_platform_registration' => '2024-02-27',
                'tcms_status' => 'Registered',
                'tcms_key' => 'SDN-008',
                'tcms_identifier' => 'TCMS-SDN-0008',
                'tcms_verification_status' => 'Verified',
                'odk_status' => 'Published',
                'connectivity_status' => 'Connected',
                'type_of_center_host' => 'LGU',
                'operational_status' => 'Operational',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'congressional_district' => 'Lone District',
                'province' => 'Dinagat Islands',
                'municipality_city' => 'San Jose',
                'barangay' => 'Poblacion',
                'center_name' => 'Dinagat Islands Provincial DTC',
                'longitude' => 125.5670,
                'latitude' => 9.9680,
                'verified' => true,
                'moa_date_of_signing' => '2023-04-18',
                'date_of_launching' => '2023-06-30',
                'date_of_platform_registration' => '2023-07-08',
                'tcms_status' => 'Registered',
                'tcms_key' => 'DIN-001',
                'tcms_identifier' => 'TCMS-DIN-0001',
                'tcms_verification_status' => 'Verified',
                'odk_status' => 'Published',
                'connectivity_status' => 'Connected',
                'type_of_center_host' => 'Provincial',
                'operational_status' => 'Operational',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'congressional_district' => 'Lone District',
                'province' => 'Dinagat Islands',
                'municipality_city' => 'Basilisa',
                'barangay' => 'Poblacion',
                'center_name' => 'Basilisa Digital Hub',
                'longitude' => 125.6070,
                'latitude' => 10.0540,
                'verified' => false,
                'moa_date_of_signing' => '2024-03-01',
                'date_of_launching' => null,
                'date_of_platform_registration' => null,
                'tcms_status' => 'Onboarding',
                'tcms_key' => 'DIN-002',
                'tcms_identifier' => 'TCMS-DIN-0002',
                'tcms_verification_status' => 'Pending',
                'odk_status' => 'Draft',
                'connectivity_status' => 'No Connection',
                'type_of_center_host' => 'LGU',
                'operational_status' => 'Not Operational',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
